{{- $secretChild := include "netdata.child.configs.secret" . }}
{{- if and .Values.child.enabled $secretChild}}
---
apiVersion: v1
kind: Secret
metadata:
  name: netdata-conf-child
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "netdata.name" . }}
    chart: {{ template "netdata.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ $secretChild | indent 2 }}
{{- end }}
